export const cities = [
  "",
  "Quang Ninh",
  "Ha Noi",
  "Bac Ninh",
  "Ha Nam",
  "Hai Duong",
  "Hai Phong",
  "Hung Yen",
  "Nam Dinh",
  "Thai Binh",
  "Vinh Phuc",
  "Ninh Binh",
  "Thanh Hoa",
  "Nghe An",
  "Ha Tinh",
  "Quang Binh",
  "Quang Tri",
  "Thua Thien Hue",
  "Da Nang",
  "Quang Nam",
  "Quang Ngai",
  "Binh Dinh",
  "Phu Yen",
  "Khanh Hoa",
  "Ninh Thuan",
  "Binh Thuan",
  "Kon Tum",
  "Gia Lai",
  "Dak Lak",
  "Dak Nong",
  "Lam Dong",
  "Ho Chi Minh city",
  "Ba Ria Vung Tau",
  "Binh Duong",
  "Binh Phuoc",
  "Dong Nai",
  "Tay Ninh",
  "An Giang",
  "Bac Lieu",
  "Ben Tre",
  "Ca Mau",
  "Can Tho",
  "Dong Thap",
  "Hau Giang",
  "Kien Giang",
  "Long An",
  "Soc Trang",
  "Tien Giang",
  "Tra Vinh",
  "Vinh Long",
];
export const colors = [
  "yellow",
  "red",
  "blue",
  "green",
  "pink",
  "gray",
  "black",
  "brown",
  "purple",
  "orange",
  "white",
];
export const brands = [
  "asus",
  "msi",
  "apple",
  "dell",
  "sony",
  "xiaomi",
  "huawai",
  "oppo",
  "samsung",
  "oneplus",
  "realme",
];

export const conditions = [
  "brand new",
  "used (hasn't been repaired)",
  "used (has been repaired)",
];

export const warranties = ["still under warranty", "expired"];
