export enum PAYMENT_STATUS {
    WAITING_FOR_PAYMENT  = "WAITING FOR PAYMENT",
    PURCHASED = "PURCHASED",
    CANCEL = "CANCEL",
}

export enum SHIPPING_STATUS {
    WAITING_FOR_SHIPPER = "WAITING_FOR_SHIPPER",
    SHIPPING = "SHIPPING",
    DELIVERED = "DELIVERED",
}