export enum SOCKET_EVENT {
    JOIN_ROOM = "JOIN_ROOM",
    RERENDER_NOTIFICATION = "RERENDER_NOTIFICATION",
    SEND_NOTIFICATION = "SEND_NOTIFICATION",
    RECEIVE_NOTIFICATION = "RECEIVE_NOTIFICATION",
}